In [2]:
import numpy as np

In [3]:
employee_id = np.arange(1000,1010)
print(employee_id)

[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009]


In [4]:
id=np.arange(3,34,4)
print(id)

[ 3  7 11 15 19 23 27 31]


In [5]:
#linspace gives n values while arange gives values with a step size
line=np.linspace(0,20,6)
print(line)

[ 0.  4.  8. 12. 16. 20.]


In [6]:
#identity matrix
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
arr=np.arange(0,15)
arr=arr.reshape(5,-1)
print(arr)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


boolean

In [8]:
marks = [45, 67, 82, 91, 39, 75, 58]

result = []

for mark in marks:
    if mark > 60:
        result.append(mark)

print(result)

[67, 82, 91, 75]


In [9]:
import numpy as np

marks = np.array([45, 67, 82, 91, 39, 75, 58])

print(marks > 60)

[False  True  True  True False  True False]


In [10]:
print(marks[marks > 60])

[67 82 91 75]


In [11]:
marks = np.array([45,67,82,91,39,75,58])
print(marks[(marks > 60) & (marks < 90)])


[67 82 75]


In [12]:
arr = np.array([5,10,15,20,25])

print(arr > 15)

[False False False  True  True]


In [13]:
import numpy as np

marks = np.array([70,80,90])

print(marks + 5)

[75 85 95]


In [14]:
arr = np.array([
    [1,2],
    [3,4]
])

print(arr+5)

[[6 7]
 [8 9]]


In [15]:
a = np.array([100,200,300])

b = np.array([10])

print(a-b)

[ 90 190 290]


In [16]:

print(np.random.randint(1,10))


6


In [17]:
np.random.rand(3)

array([0.04517512, 0.76648233, 0.24251746])

In [18]:
np.random.seed(42)

In [19]:
import numpy as np

np.random.seed(42)

print(np.random.randint(1,10))

7


In [20]:
arr=[2,5,7,4,5,2,6]
arr2=np.sort(arr)
print(arr2)

[2 2 4 5 5 6 7]


In [21]:
arr=[2,5,7,4,5,2,6]
arr3=np.argmax(arr)
print(arr3)

2


In [22]:
arr = np.array([10,20,30,20,40,20])

print(np.where(arr==20))

(array([1, 3, 5]),)


In [23]:
arr = np.array([50,20,10,40,30])
np.argsort(arr)

array([2, 1, 4, 3, 0])

In [24]:
arr = np.array([5,10,15,20])

np.where(arr>10)

(array([2, 3]),)

In [25]:
import numpy as np

a = np.array([10,20,30])
b = np.array([40,50,60])

result = np.concatenate((a,b))

print(result)

[10 20 30 40 50 60]


In [26]:
arr = np.array([10,20,30,40,50,60])

np.split(arr,3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [27]:
arr = np.array([1,2,3])

b = arr.copy()

b[0] = 10
print(arr)

[1 2 3]


In [28]:
arr = np.array([1,2,3])

b = arr.view()

b[0] = 10
print(arr)


[10  2  3]


In [29]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6]
])
print (arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [30]:
A = np.array([
    [1,2],
    [3,4]
])

B = np.array([
    [5,6],
    [7,8]
])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [31]:
np.sum(arr)

np.int64(21)

In [32]:
np.sum(arr, axis=0)  # Sum along the columns

array([5, 7, 9])

In [33]:
np.sum(arr, axis=1)  # Sum along the rows

array([ 6, 15])

In [34]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])


In [35]:
np.sum(arr)

np.int64(45)

In [36]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [37]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [38]:
np.max(arr, axis=0)

array([7, 8, 9])

In [39]:
arr = np.array([100,200,300,400,500])

print(arr[[4,2,0]])

[500 300 100]


In [40]:
import numpy as np

arr = np.array([1.2,2.5,3.8])

print(arr.dtype)

float64


In [41]:
new_arr = arr.astype(int)

print(new_arr)

[1 2 3]


In [42]:
arr = np.array([1.8,2.9,3.1])

print(arr.astype(int))

[1 2 3]


In [44]:
import numpy as np
arr= np.array([44,66,22,76,34,90,89,65,88])
results = np.where(arr>50, "Pass", "Fail")
print(results)

['Fail' 'Pass' 'Fail' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']


In [48]:
arr= np.array([-1,5,7,-4,88,-23,0])
results=np.where(arr<0, 0, arr)
print(results)

[ 0  5  7  0 88  0  0]


In [49]:
import numpy as np

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [50]:
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [52]:
fla=arr.ravel()
fla[0]=32
print(fla)

[32  2  3  4  5  6  7  8  9]


In [53]:
import numpy as np

arr = np.array([4,9,16,25])

print(np.sqrt(arr))

[2. 3. 4. 5.]


In [54]:
arr = np.array([-10,-5,8,-3])   #negative becomes positive

print(np.abs(arr)) 

[10  5  8  3]


In [55]:
arr = np.array([1,10,100])  #gives the log values

print(np.log(arr))

[0.         2.30258509 4.60517019]


In [56]:
numbers = [1,2,3,4]
print(numbers*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [57]:
import numpy as np

arr = np.array([10,20,30,40])

print(arr.shape)

(4,)


In [58]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.ndim)

2


In [59]:
arr = np.array([10,20,30,40,50])

print(arr[-2])

40


In [60]:
arr = np.array([10,20,30,40,50])

print(arr[1:4])

[20 30 40]


In [61]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[1,2])

60


In [62]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(arr[:,1])

[20 50 80]
