In [2]:
import numpy as np

In [4]:
employee_id = np.arange(1000,1010)
print(employee_id)

[1000 1001 1002 1003 1004 1005 1006 1007 1008 1009]


In [5]:
id=np.arange(3,34,4)
print(id)

[ 3  7 11 15 19 23 27 31]


In [ ]:
#linspace gives n values while arange gives values with a step size
line=np.linspace(0,20,6)
print(line)

[ 0.  4.  8. 12. 16. 20.]


In [9]:
#identity matrix
identity=np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
arr=np.arange(0,15)
arr=arr.reshape(5,-1)
print(arr)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


boolean

In [17]:
marks = [45, 67, 82, 91, 39, 75, 58]

result = []

for mark in marks:
    if mark > 60:
        result.append(mark)

print(result)

[67, 82, 91, 75]


In [18]:
import numpy as np

marks = np.array([45, 67, 82, 91, 39, 75, 58])

print(marks > 60)

[False  True  True  True False  True False]


In [19]:
print(marks[marks > 60])

[67 82 91 75]


In [20]:
marks = np.array([45,67,82,91,39,75,58])
print(marks[(marks > 60) & (marks < 90)])


[67 82 75]


In [21]:
arr = np.array([5,10,15,20,25])

print(arr > 15)

[False False False  True  True]


In [3]:
import numpy as np

marks = np.array([70,80,90])

print(marks + 5)

[75 85 95]


In [23]:
arr = np.array([
    [1,2],
    [3,4]
])

print(arr+5)

[[6 7]
 [8 9]]


In [24]:
a = np.array([100,200,300])

b = np.array([10])

print(a-b)

[ 90 190 290]


In [4]:

print(np.random.randint(1,10))


4


In [18]:
np.random.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

In [17]:
np.random.seed(42)

In [16]:
import numpy as np

np.random.seed(42)

print(np.random.randint(1,10))

7


In [19]:
arr=[2,5,7,4,5,2,6]
arr2=np.sort(arr)
print(arr2)

[2 2 4 5 5 6 7]


In [21]:
arr=[2,5,7,4,5,2,6]
arr3=np.argmax(arr)
print(arr3)

2


In [25]:
arr = np.array([10,20,30,20,40,20])

print(np.where(arr==20))

(array([1, 3, 5]),)


In [26]:
arr = np.array([50,20,10,40,30])
np.argsort(arr)

array([2, 1, 4, 3, 0])

In [27]:
arr = np.array([5,10,15,20])

np.where(arr>10)

(array([2, 3]),)

In [28]:
import numpy as np

a = np.array([10,20,30])
b = np.array([40,50,60])

result = np.concatenate((a,b))

print(result)

[10 20 30 40 50 60]


In [29]:
arr = np.array([10,20,30,40,50,60])

np.split(arr,3)

[array([10, 20]), array([30, 40]), array([50, 60])]

In [32]:
arr = np.array([1,2,3])

b = arr.copy()

b[0] = 10
print(arr)

[1 2 3]


In [33]:
arr = np.array([1,2,3])

b = arr.view()

b[0] = 10
print(arr)


[10  2  3]
